gcloud functions deploy addToFirestoreRecipeAutoGeneratedByAI --env-vars-file .env.yaml \
    --gen2 \
    --trigger-http \
    --entry-point add_to_firestore_recipe_auto_generated_by_ai \
    --region asia-northeast1 \
    --source addToFirestoreRecipeAutoGeneratedByAI/ \
    --runtime python312 \
    --allow-unauthenticated \