// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJkBA6Q4hydxb4PvLLPWIEbOD9mjUFXc',
    appId: '1:203960912563:web:9d2aafd7e9bcac3eecbec6',
    messagingSenderId: '203960912563',
    projectId: 'cook-helper-b246c',
    authDomain: 'cook-helper-b246c.firebaseapp.com',
    storageBucket: 'cook-helper-b246c.appspot.com',
    measurementId: 'G-DD69X32NZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMd0gla5L5RxDa1WxGJsXa82NP9U3lVQ',
    appId: '1:203960912563:android:dacb3c8e2b8545faecbec6',
    messagingSenderId: '203960912563',
    projectId: 'cook-helper-b246c',
    storageBucket: 'cook-helper-b246c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqa1mPmtI1iN4578dlmsGUmocfO_ykow',
    appId: '1:203960912563:ios:bcc2f98b0c9df864ecbec6',
    messagingSenderId: '203960912563',
    projectId: 'cook-helper-b246c',
    storageBucket: 'cook-helper-b246c.appspot.com',
    iosBundleId: 'com.example.cookHelperMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqa1mPmtI1iN4578dlmsGUmocfO_ykow',
    appId: '1:203960912563:ios:bcc2f98b0c9df864ecbec6',
    messagingSenderId: '203960912563',
    projectId: 'cook-helper-b246c',
    storageBucket: 'cook-helper-b246c.appspot.com',
    iosBundleId: 'com.example.cookHelperMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJkBA6Q4hydxb4PvLLPWIEbOD9mjUFXc',
    appId: '1:203960912563:web:dc88fb32100f13dbecbec6',
    messagingSenderId: '203960912563',
    projectId: 'cook-helper-b246c',
    authDomain: 'cook-helper-b246c.firebaseapp.com',
    storageBucket: 'cook-helper-b246c.appspot.com',
    measurementId: 'G-T3281F1M9F',
  );

}